// ── 실제 분석 수치 반영 (영천시 축제 공간경제 효과 분석, 2022–2024) ──

export const dataSources = {
  visitorsPopulation: [
    {
      name: "한국관광 데이터랩 (KTDB)",
      org: "한국관광공사",
      url: "datalab.visitkorea.or.kr",
      unit: "시·군·구 / 월별",
      cost: "무료",
      note: "3사 통합 추정치. 방문자수·숙박률·체류시간·유입출발지 데이터 제공. 본 분석의 핵심 데이터 소스.",
      tag: "핵심",
      tagColor: "#d64f2a",
    },
    {
      name: "생활인구 통계 (SGIS)",
      org: "행정안전부 · 통계청",
      url: "sgis.kostat.go.kr",
      unit: "읍·면·동 / 일별·시간대",
      cost: "무료",
      note: "SKT 협력 기반. 읍면동 × 시간대(1시간) × 성별·연령 5구간. 비회원도 집계표 다운로드 가능.",
      tag: "핵심",
      tagColor: "#d64f2a",
    },
    {
      name: "경북 빅데이터 관광통계",
      org: "경상북도",
      url: "bigdata.gb.go.kr",
      unit: "시·군 / 월별",
      cost: "무료(회원)",
      note: "경북 특화 관광 분석. 영천시 단위 방문객 집계 포함.",
      tag: "지역",
      tagColor: "#0ea86e",
    },
    {
      name: "주민등록 인구통계",
      org: "행정안전부",
      url: "jumin.mois.go.kr",
      unit: "읍·면·동 / 월별",
      cost: "무료",
      note: "체류인구 전환 시 거주자 차감의 기준값(Step 1). 월별 CSV 다운로드 가능.",
      tag: "기준값",
      tagColor: "#888",
    },
    {
      name: "공공데이터포털 (관광통계 API)",
      org: "행정안전부",
      url: "data.go.kr",
      unit: "관광지 / 수시",
      cost: "무료(API 키)",
      note: "TourAPI 연동. 입장객 통계, 관광지 기초현황 REST API.",
      tag: "API",
      tagColor: "#1a56db",
    },
  ],
  consumption: [
    {
      name: "소상공인 상권정보 시스템",
      org: "소상공인진흥공단",
      url: "sg.sbiz.or.kr",
      unit: "업종·읍면동 / 분기",
      cost: "무료",
      note: "본 분석 활용(2023Q2). 영천시 전체 4,833개 상가 분포 분석. 완산동 809개·야사동 611개·문외동 442개 확인.",
      tag: "핵심",
      tagColor: "#d64f2a",
    },
    {
      name: "카드 매출 통계 (지역별)",
      org: "여신금융협회",
      url: "card.or.kr",
      unit: "시·도 / 월별",
      cost: "무료",
      note: "광역 단위 카드 소비 추세 파악. 업종별 이용건수·금액 월별 제공.",
      tag: "보조",
      tagColor: "#888",
    },
    {
      name: "산업연관표 (ECOS)",
      org: "한국은행",
      url: "ecos.bok.or.kr",
      unit: "산업 / 5년 주기",
      cost: "무료",
      note: "생산·부가가치·취업 유발 계수 산출 기준표. 지역산업연관표 별도 제공(5년 주기).",
      tag: "핵심",
      tagColor: "#d64f2a",
    },
    {
      name: "지역 내 총생산 (GRDP) - KOSIS",
      org: "통계청",
      url: "kosis.kr",
      unit: "시·도 / 연별",
      cost: "무료",
      note: "경제 파급효과를 GRDP 대비 비율로 표현 시 기준값.",
      tag: "보조",
      tagColor: "#888",
    },
  ],
  social: [
    {
      name: "네이버 데이터랩 (검색 트렌드)",
      org: "네이버",
      url: "datalab.naver.com",
      unit: "키워드 / 일별",
      cost: "무료",
      note: "축제명 검색량 추이. 기간·기기·성별·연령 교차 분석. 상대 지수(0~100) 제공.",
      tag: "추천",
      tagColor: "#1a56db",
    },
    {
      name: "네이버 블로그·카페 OpenAPI",
      org: "네이버 개발자센터",
      url: "developers.naver.com",
      unit: "포스팅 / 실시간",
      cost: "무료(API 키)",
      note: "키워드 검색 결과 JSON 반환. 제목·내용·날짜·URL 수집. 일 25,000건 무료.",
      tag: "추천",
      tagColor: "#1a56db",
    },
    {
      name: "카카오맵 로컬 API",
      org: "카카오 개발자",
      url: "developers.kakao.com",
      unit: "장소 리뷰 / 실시간",
      cost: "무료(API 키)",
      note: "장소 ID 기반 리뷰 텍스트·별점 수집. 월 300,000회 무료.",
      tag: "추천",
      tagColor: "#1a56db",
    },
    {
      name: "빅카인즈 뉴스 분석",
      org: "한국언론진흥재단",
      url: "bigkinds.or.kr",
      unit: "기사 / 실시간",
      cost: "무료(회원)",
      note: "전국 언론사 기사 통합. 키워드 트렌드, 연관어 네트워크, 감성 분석 제공.",
      tag: "추천",
      tagColor: "#1a56db",
    },
  ],
  spatial: [
    {
      name: "국토정보플랫폼 (행정경계 SHP)",
      org: "국토지리정보원",
      url: "map.ngii.go.kr",
      unit: "읍·면·동 / 연별",
      cost: "무료",
      note: "본 분석 활용. 2023년 7월 기준 읍면동 경계 SHP. 소상공인 데이터와 결합하여 반경 버퍼 분석 수행.",
      tag: "핵심",
      tagColor: "#d64f2a",
    },
    {
      name: "기상 관측 자료 (ASOS)",
      org: "기상청",
      url: "data.kma.go.kr",
      unit: "지점 / 시간별",
      cost: "무료",
      note: "영천 기상관측소 데이터. 기온·강수량·일조시간. API 및 CSV 다운로드 모두 지원.",
      tag: "추천",
      tagColor: "#1a56db",
    },
    {
      name: "TourAPI (관광지 기초현황)",
      org: "한국관광공사",
      url: "apis.data.go.kr/B551011",
      unit: "관광지 / 수시",
      cost: "무료(API 키)",
      note: "영천 인근 관광자원 위치·유형·편의시설. REST API, JSON/XML 응답.",
      tag: "API",
      tagColor: "#1a56db",
    },
    {
      name: "도로 교통량 통계 (ITS)",
      org: "국토교통부",
      url: "its.go.kr",
      unit: "구간 / 연별",
      cost: "무료",
      note: "축제 기간 주요 진입로(경부고속도·중앙고속도) 교통량 변화 분석.",
      tag: "보조",
      tagColor: "#888",
    },
  ],
  survey: [
    {
      name: "지역 축제 실태 조사",
      org: "문화체육관광부",
      url: "mcst.go.kr",
      unit: "축제별 / 연별",
      cost: "무료",
      note: "전국 지역 축제 방문객·예산·프로그램 현황. 벤치마킹·비교 분석 기준값.",
      tag: "추천",
      tagColor: "#1a56db",
    },
    {
      name: "관광객 실태 조사 원시 데이터",
      org: "한국관광공사",
      url: "data.visitkorea.or.kr",
      unit: "개인 응답 / 연별",
      cost: "무료(회원)",
      note: "마이크로 데이터. SEM·회귀 분석 직접 활용 가능. 연별 표본 약 20,000명.",
      tag: "추천",
      tagColor: "#1a56db",
    },
  ],
};

// ── 체류인구 전환 6단계 ────────────────────────────────────────
export const stayPopulationSteps = [
  {
    id: "01", title: "기준인구 설정",
    desc: "읍·면·동별 주민등록 인구(등록인구) 추출",
    source: "행정안전부 주민등록 인구통계 — jumin.mois.go.kr",
    note: "월별 기준. 거주자 차감 분모로 사용.",
    color: "#d64f2a",
  },
  {
    id: "02", title: "생활인구 취득",
    desc: "축제 기간(5·10월) + 베이스라인(3월) 생활인구 다운로드",
    source: "KTDB — datalab.visitkorea.or.kr / SGIS 생활인구",
    note: "3월 베이스라인 선정 이유: 추석 연휴 없는 영천시 비축제 평시.",
    color: "#1a56db",
  },
  {
    id: "03", title: "거주자 제거",
    desc: "생활인구에서 등록인구(추정 거주자) 차감",
    source: "Step 01 + Step 02 결합",
    note: "외부 방문객 = 생활인구 × (1 – 거주자 비율)",
    color: "#7c3aed",
  },
  {
    id: "04", title: "축제 유인 효과 분리",
    desc: "축제 달(5·10월) – 베이스라인(3월) = 순증 방문객",
    source: "Step 02 시계열 비교",
    note: "실제 결과: 베이스라인 893,341명 → 가을축제 1,024,962명 (+14–15%)",
    color: "#0ea86e",
  },
  {
    id: "05", title: "체류시간 필터",
    desc: "1시간 미만 통과인구 제외, 1시간 이상 체류자만 집계",
    source: "KTDB 기본값(1시간) / SGIS 체류시간 필드",
    note: "※주의: 3월 평균 1,478분(24.6h) > 5월 1,075분(17.9h). 비수기 장기체류 편중 효과.",
    color: "#f0b429",
  },
  {
    id: "06", title: "보정계수 적용",
    desc: "단말 미소지자·영유아 비율 반영 → 전체 인구 환산",
    source: "방통위 인터넷 이용실태조사 (연령별 보급률)",
    note: "스마트폰 보급률 약 93% 적용 → 추정값 ÷ 0.93",
    color: "#d64f2a",
  },
];

// ── 실제 분석 결과 수치 ──────────────────────────────────────
export const analysisResults = {
  visitors: {
    baseline: { label: "베이스라인(3월)", value: 893341, color: "#95a5a6" },
    herb:     { label: "한약축제(5월)",   value: 1019241, color: "#2ecc71" },
    autumn:   { label: "가을축제(10월)",  value: 1024962, color: "#e74c3c" },
    increaseRate: "14–15%",
  },
  stayTime: {
    baseline: { label: "베이스라인(3월)", minutes: 1478, color: "#95a5a6" },
    herb:     { label: "한약축제(5월)",   minutes: 1075, color: "#2ecc71" },
    autumn:   { label: "가을축제(10월)",  minutes: 1077, color: "#e74c3c" },
  },
  accommodation: {
    baseline: { label: "베이스라인(3월)", rate: 8.2, color: "#95a5a6" },
    herb:     { label: "한약축제(5월)",   rate: 9.0, color: "#2ecc71" },
    autumn:   { label: "가을축제(10월)",  rate: 8.7, color: "#e74c3c" },
  },
  inflow: [
    { region: "경상북도 경산시", ratio: 19.5 },
    { region: "대구광역시 동구", ratio: 12.0 },
    { region: "대구광역시 수성구", ratio: 10.6 },
    { region: "경상북도 경주시", ratio: 9.8 },
    { region: "대구광역시 북구", ratio: 7.2 },
    { region: "대구광역시 달서구", ratio: 6.4 },
    { region: "경상북도 포항시 북구", ratio: 5.1 },
    { region: "경상북도 포항시 남구", ratio: 4.8 },
    { region: "대구광역시 군위군", ratio: 3.6 },
    { region: "경상북도 구미시", ratio: 3.2 },
  ],
  buffer: [
    { festival: "보현산별빛축제", km1: 0,    km3: 16,   km5: 35,   color: "#7c3aed", note: "산간 입지 — 낙수 구조 자체 부재" },
    { festival: "한약축제",       km1: 1583, km3: 3060, km5: 3394, color: "#2ecc71", note: "상권 접근성 충분, 체류 유도 필요" },
    { festival: "와인·한우·예술제", km1: 1524, km3: 3037, km5: 3363, color: "#e74c3c", note: "상권 접근성 충분, 체류 유도 필요" },
  ],
};

// ── 4대 결론 ────────────────────────────────────────────────
export const conclusions = [
  {
    id: "01",
    title: "방문자 유입 효과는 실재한다",
    desc: "축제 달 방문자수는 베이스라인 대비 14–15% 증가. 베이스라인 893,341명 → 가을축제 1,024,962명으로 외지인 유입에 유의미한 효과 확인.",
    color: "#2ecc71",
    icon: "✅",
    badge: "유입 +14–15%",
  },
  {
    id: "02",
    title: "체류·숙박 전환에 실패하고 있다",
    desc: "축제 달 체류시간(1,075분)이 오히려 비축제 달(1,478분)보다 짧고, 숙박률도 8.2%→9.0%로 증가폭이 미미. 당일 방문 편중 현상이 낙수효과의 구조적 한계를 만든다.",
    color: "#e74c3c",
    icon: "⚠️",
    badge: "숙박률 격차 0.8%p",
  },
  {
    id: "03",
    title: "소비 낙수효과는 업종별로 불균등하다",
    desc: "식음료업 +27.6%, 쇼핑업 +23.3%는 증가하지만 숙박업 증가폭은 미미. 고부가가치 소비 유발에 실패하고 있다.",
    color: "#f0b429",
    icon: "📊",
    badge: "식음료 +27.6%",
  },
  {
    id: "04",
    title: "공간적 낙수 여건이 축제별로 상이하다",
    desc: "보현산별빛축제는 1km 내 상가 0개로 낙수 구조 자체 부재. 도심 축제(한약·와인·한우)는 1,500개 이상 상권 밀집이나 체류 부족으로 잠재력 미실현.",
    color: "#7c3aed",
    icon: "🗺️",
    badge: "보현산 1km: 0개",
  },
];

// ── 4대 정책 제언 ────────────────────────────────────────────
export const policyRecommendations = [
  {
    id: "01",
    title: "보현산별빛축제 연계 상권 개발",
    desc: "산간 입지로 상권 전무 → 축제 기간 한시적 로컬 마켓·푸드트럭 존 조성. 보현산 방문객을 영천 도심 상권으로 연결하는 셔틀버스 노선과 연계 쿠폰 프로그램 도입.",
    color: "#7c3aed",
    tag: "공간 전략",
  },
  {
    id: "02",
    title: "체류형 관광 전환 인프라 강화",
    desc: "한약축제·가을축제는 상권 접근성 충분하나 당일 편중이 문제. 야간 프로그램 확대, 숙박 패키지 연계 할인, 2일권 관람 프로그램 도입으로 1박 이상 체류 유도.",
    color: "#e74c3c",
    tag: "체류 유도",
  },
  {
    id: "03",
    title: "광역 유입 확대 전략",
    desc: "현재 방문객 40% 이상이 대구·경북 인접 지역 유입. 수도권·부산·울산 등 원거리 방문객 유치를 위한 광역 마케팅 강화와 KTX 연계 관광 상품 개발 필요.",
    color: "#2ecc71",
    tag: "마케팅",
  },
  {
    id: "04",
    title: "데이터 기반 정기 모니터링 체계 수립",
    desc: "본 연구의 분석 프레임워크(KTDB×소상공인×공간데이터)를 매년 정기 적용. 축제 효과 변화 추이 추적 및 정책 효과 검증을 위한 상시 모니터링 체계 구축.",
    color: "#1a56db",
    tag: "거버넌스",
  },
];

// ── 시각화 기법 ──────────────────────────────────────────────
export const vizTechniques = [
  {
    id: "flow",
    category: "공간",
    title: "OD Flow Map",
    subtitle: "출발지-도착지 흐름 지도",
    desc: "방문객 출발지(시·군·구) → 영천 축제장을 연결하는 곡선 흐름선. 경산시(19.5%)·대구 동구(12.0%)·수성구(10.6%) 등 주요 유입 경로 시각화.",
    tools: ["Python kepler.gl", "QGIS OD Matrix", "Deck.gl ArcLayer"],
    inputs: ["KTDB 출발지별 방문객", "행정경계 SHP"],
    outputs: ["광역 방문 패턴 시각화", "마케팅 타겟 권역 도출"],
    difficulty: "중",
    impact: "상",
    color: "#d64f2a",
  },
  {
    id: "buffer",
    category: "공간",
    title: "동심원 버퍼 분석",
    subtitle: "축제장 반경별 상권 분포",
    desc: "축제장 기준 1km·3km·5km 버퍼 내 상가 수 분석. 보현산(1km: 0개) vs 한약축제(1km: 1,583개) — 낙수 구조의 공간적 불균형을 정량적으로 규명.",
    tools: ["Python geopandas", "QGIS Buffer", "소상공인 상가데이터"],
    inputs: ["소상공인 상가업소(2023Q2)", "읍면동 경계 SHP"],
    outputs: ["축제별 낙수효과 구조 비교", "상권 접근성 지도"],
    difficulty: "중",
    impact: "상",
    color: "#7c3aed",
  },
  {
    id: "kde",
    category: "공간",
    title: "커널 밀도 추정 (KDE)",
    subtitle: "방문객 밀집 핫스팟 히트맵",
    desc: "통신사 기지국 좌표 × 방문객 수를 가우시안 커널로 평활화. 완산동·야사동·문외동 도심 집중 구조를 연속 밀도 면으로 표현.",
    tools: ["Python scipy.stats.gaussian_kde", "QGIS Heatmap", "geopandas + folium"],
    inputs: ["SGIS 생활인구(읍면동·시간대)", "행정경계 SHP"],
    outputs: ["시간대별 혼잡도 애니메이션", "시설 배치 개선안"],
    difficulty: "중",
    impact: "상",
    color: "#d64f2a",
  },
  {
    id: "moran",
    category: "공간",
    title: "공간 자기상관 (Moran's I)",
    subtitle: "소비 클러스터 LISA 지도",
    desc: "읍·면·동별 축제 기간 매출 증가율에 대해 Local Moran's I를 계산. HH(고-고)·LL(저-저)·HL·LH 4개 클러스터를 LISA 지도로 표현.",
    tools: ["Python pysal / esda", "R spdep", "GeoDa (무료 GIS)"],
    inputs: ["소상공인 상권정보 매출", "행정경계 SHP"],
    outputs: ["상권 활성 클러스터 지도", "수혜 취약 지역 식별"],
    difficulty: "상",
    impact: "상",
    color: "#7c3aed",
  },
  {
    id: "timeline",
    category: "시계열",
    title: "STL 분해 + Prophet 예측",
    subtitle: "방문객 추세·계절성 분해 차트",
    desc: "KTDB 월별 방문객 시계열(2022–2024)을 STL로 추세·계절성·잔차 3개 패널로 분해. Prophet으로 향후 3년 예측선 및 신뢰구간 오버레이.",
    tools: ["Python prophet", "statsmodels STL", "matplotlib / plotly"],
    inputs: ["KTDB 3개년 방문객 시계열"],
    outputs: ["3년 방문객 예측값", "계절 피크 시점 근거"],
    difficulty: "중",
    impact: "중",
    color: "#0ea86e",
  },
  {
    id: "sentiment",
    category: "텍스트",
    title: "시계열 감성 추이 차트",
    subtitle: "SNS 긍정/부정 비율 변화",
    desc: "네이버 블로그·카카오맵 리뷰를 KoBERT로 감성 분류 후, 축제 전 2주~후 4주 구간별 긍정·부정 비율을 누적 면적 차트로 시각화.",
    tools: ["KoNLPy Mecab", "HuggingFace KoBERT", "Python plotly"],
    inputs: ["네이버 OpenAPI", "카카오맵 로컬 API"],
    outputs: ["감성 점수 시계열", "부정 급증 원인 키워드"],
    difficulty: "상",
    impact: "상",
    color: "#0ea86e",
  },
  {
    id: "sankey",
    category: "흐름",
    title: "Sankey 다이어그램",
    subtitle: "방문객 여정·지출 흐름도",
    desc: "출발지 → 교통수단 → 방문 목적 → 지출 항목(식음료 +27.6%, 쇼핑 +23.3%, 숙박 제한적)의 흐름을 Sankey 다이어그램으로 표현.",
    tools: ["Python plotly (Sankey)", "D3.js sankey plugin", "R ggalluvial"],
    inputs: ["KTDB 방문객 속성", "관광소비 업종 데이터"],
    outputs: ["방문객 여정 전체 파악", "주요 지출 카테고리 도출"],
    difficulty: "중",
    impact: "상",
    color: "#7c3aed",
  },
  {
    id: "ipa",
    category: "통계",
    title: "IPA 매트릭스",
    subtitle: "중요도-성과 2×2 사분면",
    desc: "설문 5점 리커트 데이터로 각 서비스 속성의 중요도(X)·만족도(Y)를 산점도에 배치. 전체 평균을 기준선으로 4개 사분면으로 구분.",
    tools: ["Python matplotlib / seaborn", "R ggplot2"],
    inputs: ["현장 설문(400부 이상)", "5점 리커트 이원 측정"],
    outputs: ["개선 우선순위 매트릭스", "예산 배분 근거"],
    difficulty: "하",
    impact: "상",
    color: "#1a56db",
  },
  {
    id: "radar",
    category: "통계",
    title: "레이더 차트 (연도별 비교)",
    subtitle: "축제 경쟁력 다차원 비교",
    desc: "방문객 수·경제효과·SNS 언급량·만족도·접근성·프로그램 다양성 등 6개 축으로 레이더 차트 구성. 연도별 또는 타 지역 축제와 중첩 비교.",
    tools: ["Python plotly / matplotlib", "R fmsb"],
    inputs: ["KTDB 연도별", "문체부 실태조사", "설문 만족도"],
    outputs: ["연도별 성장 패턴 비교", "타 축제 벤치마킹"],
    difficulty: "하",
    impact: "중",
    color: "#f0b429",
  },
];

// ── 분석 방법론 ───────────────────────────────────────────────
export const analysisMethodologies = [
  {
    id: "io", title: "투입-산출 분석", subtitle: "Input-Output Analysis",
    category: "경제효과", categoryColor: "#d64f2a",
    desc: "레온티에프 모형 기반. 방문객 지출이 지역 경제 각 산업에 미치는 연쇄 효과를 정량화.",
    formulas: ["생산 유발 = 지출액 × 생산 유발 계수", "부가가치 유발 = 지출액 × 부가가치 유발 계수", "취업 유발 = 지출액 × 취업 유발 계수 (명/10억 원)"],
    tools: ["한국은행 ECOS (무료)", "Python pandas", "지역산업연관표"],
  },
  {
    id: "quasi", title: "준실험 설계", subtitle: "Quasi-Experimental Design",
    category: "인과추론", categoryColor: "#e74c3c",
    desc: "3월(베이스라인) vs 5·10월(축제 달) 비교. 3월 선정 이유: 추석 연휴 없는 영천시 비축제 평시. 2020–2021년(코로나) 제외.",
    formulas: ["순증 방문객 = 축제 달 – 베이스라인(3월)", "결과: +126,000명(한약) / +131,621명(가을)", "계절성 통제: 동일 요일 3개년 평균 대조"],
    tools: ["Python pandas (무료)", "비교 설계", "KTDB 2022–2024"],
  },
  {
    id: "spatial", title: "공간 버퍼 분석", subtitle: "Buffer & Choropleth",
    category: "공간", categoryColor: "#7c3aed",
    desc: "소상공인 상가 데이터(2023Q2, 4,833개)와 읍면동 경계 SHP를 결합. 1km·3km·5km 동심원 버퍼 내 상권 분포 분석.",
    formulas: ["보현산 1km: 0개 / 3km: 16개 / 5km: 35개", "한약축제 1km: 1,583개 / 3km: 3,060개", "와인·한우 1km: 1,524개 / 3km: 3,037개"],
    tools: ["Python geopandas (무료)", "QGIS (무료)", "소상공인 오픈데이터"],
  },
  {
    id: "ipa", title: "IPA 분석", subtitle: "Importance-Performance Analysis",
    category: "만족도", categoryColor: "#1a56db",
    desc: "중요도·성과를 2×2 매트릭스로 시각화. Grand Mean 기준점 설정.",
    formulas: ["집중개선: 중요도 高 × 성과 低 → 최우선", "현수준유지: 중요도 高 × 성과 高", "기준점: Grand Mean 방식"],
    tools: ["Python matplotlib (무료)", "R ggplot2 (무료)", "SPSS"],
  },
  {
    id: "sem", title: "구조방정식 모형", subtitle: "SEM",
    category: "행동 의도", categoryColor: "#7c3aed",
    desc: "잠재변수(만족도·재방문·이미지) 간 인과관계 동시 검증.",
    formulas: ["측정 모형: CFA (확인적 요인분석)", "구조 모형: 경로계수 유의성", "매개 효과: 품질 → 만족도 → 재방문"],
    tools: ["SmartPLS (무료체험)", "R lavaan (무료)", "AMOS"],
  },
  {
    id: "prophet", title: "시계열 예측", subtitle: "ARIMA / Prophet / STL",
    category: "수요 예측", categoryColor: "#0ea86e",
    desc: "연도별 방문객 시계열로 미래 수요 예측 및 계절성 분해.",
    formulas: ["ARIMA: 단기 자기회귀 예측", "Prophet: 연간 계절성 + 특수일", "STL 분해: 추세·계절성·잔차"],
    tools: ["Python statsmodels (무료)", "Meta Prophet (무료)", "R forecast (무료)"],
  },
  {
    id: "text", title: "텍스트 마이닝", subtitle: "Text Mining & Sentiment",
    category: "소셜", categoryColor: "#0ea86e",
    desc: "형태소 분석 → TF-IDF → LDA → KoBERT 감성 분류.",
    formulas: ["형태소 분석 → TF-IDF → 키워드", "LDA 토픽 모델링", "KoBERT 감성 분류 (긍정/부정)"],
    tools: ["KoNLPy Mecab (무료)", "HuggingFace KoBERT (무료)", "Python gensim (무료)"],
  },
];
